### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by patleb** [mavenlink/alaska#18]
Having version 1.2.0 released to RubyGems would be nice.

Thx

**Comment by diclophis** [comment]
Indeed, we will process a new version and publish to gem by the end of the week

**Comment by patleb** [comment]
These are the commands that you might be looking for:

```bash
gem build alaska.gemspec
```
```bash
gem push alaska-1.2.0.gem
```

But, actually, it doesn't matter much anymore, I'm using [ext_bundler](https://github.com/patleb/ext_bundler) from now on.

**Comment by diclophis** [comment]
Yea, we had to shuffle this repo around in the org, and we are working through a little bit of automation around publishing releases automatically from the master branch.. and we needed to dig up our rubygems credentials from our secure archives.

In general this project has been sidechanneld mostly due to our recent adoption of `yarn` ... We would be super interested in your use-case for `alaska` as it provides further context in the direction we would want to take this project... at the moment the uses cases I have in mind are

```
1) Legacy rails4/5 application with _too many_ js files to parse quickly via the other `execjs` runtimes.
2) As the server-side backend for `react-rails` and other frameworks isomorphic rendering pipelines (we ran some benchmarks and there is evidence that `alaska` is faster than other existing runtimes
3) ... some other yet to be determined use case that you or another org might have for the project?
```

Please stand by for a gem push here shortly

**Comment by patleb** [comment]
Got it.

I can confirm that js compilation is faster with Alaska (about twice as fast the last time I tested). My use case is that we don't use webpack yet, our dev stack is fast enough with:

- sprockets
- alaska
- [turbodev](https://github.com/patleb/ext-rails/blob/master/lib/ext_rails/action_dispatch/middleware/turbo_dev.rb)
- `config.assets.debug = false`
- `config.assets.digest = false`

As for the speed, we consistently have these numbers in dev mode:

- a full page load with recompilation and an empty tmp/cache/assets dir takes under 3 seconds
- a full page load with recompilation takes under 1.5 seconds
- a full page load without recompilation takes under 1 second

for a js file size around 1.7Mb in dev and 170Kb in production for most of our apps.

**Comment by diclophis** [comment]
ok, we have just published https://rubygems.org/gems/alaska/versions/1.2.2

**Comment by patleb** [comment]
:thumbsup:
