### ISSUE TITLE
socket connection error

### ISSUE THREAD

**Issue by xjustin13** [mavenlink/alaska#21]
I get `ActionView::Template::Error (unable to connect to alaska.js server):` in Rails production log after about 30 hits to the site. I'm using this gem not just to compile assets during deployment, but actually calling a JavaScript function repeatedly on the fly. I do like `CONTEXT = ExecJS.compile(source)` once at boot, and then repeatedly do `CONTEXT.call('someFunction', some_arg)` whenever someone hits the site. I'm using `Ruby 2.0.0-p648, Rails 3.2.22, Phusion Passenger 4.0.60, on FreeBSD 11.4`. I get no issues when running in development mode, nor do I get any issues with just `execjs` gem.

**Comment by diclophis** [comment]
Is there any extra detail if you utilize the debug option? `Alaska::Runtime.new(:debug => true)`

**Comment by diclophis** [comment]
Ok, I have prepared a "stress test" of sorts in this PR https://github.com/mavenlink/alaska/pull/24 ... if you are able to run that within a similar environment as your production environment we can see if there is anything broken in that sense.

My second hunch is that it might be as simple as some bug _within_ the `source` code your system is sending through the execjs bridge ... are you allowing direct user-input into this value? is it possible to debug print all of the inbound javascript and log that leading up to the bug?

My third hunch is that maybe the execution environment within `Phusion Passenger` is "hostile" to sub-processes of the "web worker process" ... that is to say, perhaps there are safety guards built into phusion passengers mechanism that reap/collect any subprocesses created during the ruby/web request life cycle... and this is killing the secondary `nodejs` process, and thus breaking the bridge.

It may also be something as silly as the nodejs process reaching some memory threshold and being interrupted by the kernel or something?

**Comment by diclophis** [comment]
@xjustin13 ... bummer ... at this point I would have to say that the compatible with your current setup and the `alaska` gem is basically non existent... If possible could you upgrade to a more recent version of ruby and nodejs ... the known good combinations are. `ruby2..7` `node14` `linux+ubuntu18` ... outside of this platform I am not sure how we could help support your integration ... I am willing to review any patches that achieve more backwards compatibility... but I have no resources to continue the investigation into this error.

On supported platforms, the `alaska` gems test suite runs to completion, without any error/warning messages.

these messages are highly suspect as being the root cause of the compatibility issue
```
1: 0xa3e7c0 node::Abort(void) [/usr/local/bin/node]
 2: 0xa0c630 node::PlatformInit(void) [/usr/local/bin/node]
 3: 0xa0b5f5 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags) [/usr/local/bin/node]
E 1: 0xa3e7c0 node::Abort(void) [/usr/local/bin/node]
```

**Comment by xjustin13** [comment]
@diclophis Is there a temporary solution until we can come up with a long-term one? For example, can we restart the Node process if there's an error? It's just infeasible to upgrade the entire stack right now.

**Comment by diclophis** [comment]
restarting the nodejs process during runtime is effectively the same operational pattern as vanilla `execjs` gem.

I am not opposed to reviewing a patch to restart the failed nodejs process... but, it does indicate that something else is wrong and somewhat outside of the scope of this project.
